# base image with Node.js for development
FROM node:22-alpine

WORKDIR /app

#copy only dependency files first(cache optimization)
COPY package*.json ./

#intall dependencies
RUN npm install

#copy application source code
COPY src ./src  

#expose dev server port 
EXPOSE 3000 

#Start dev server(hot reload)
CMD ["npm", "run", "dev"]
