name: Provision Prod Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::910541869155:role/github-actions-role
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/environments/prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/environments/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/environments/prod